### ISSUE TITLE
真的能用吗？

### ISSUE THREAD

**Issue by maggie-chen** [notbucai/wxmini-to-vue#1]
entryPath 我指向了 pages/xxx ，但是 this._getDirList(path.resolve(entry)) 为 []

**Comment by notbucai** [comment]
可以试试直接指向pages

**Comment by maggie-chen** [comment]
> 可以试试直接指向pages
还是不行呢

const path = require('path')
// 导入 wxmini-to-vue
const WTV = require('wxmini-to-vue')
// 实例化
const wtv = new WTV()
// 入口路径
const entryPath = path.resolve(__dirname, '../dist/pages')
// 存放位置
const outputPath = path.resolve(__dirname, '../output')
// 执行转换
wtv.transform(entryPath, outputPath)

**Comment by notbucai** [comment]
方便给个例子吗

**Comment by notbucai** [comment]
这边重新指向代码测试 并为发现问题，请查看 test 目录中示例

**Comment by maggie-chen** [comment]
xx项目下 /dist（小程序文件） /scripts（编译脚本） /output (输出结果)，代码就如上面的例子一样

**Comment by notbucai** [comment]
可以加一下微信我给你看一下。
wuxin-liao

**Comment by maggie-chen** [comment]
const list = this._getDirList(path.resolve(entry)) 这里为空
